### ISSUE TITLE
Unable to use the bundle in front-office context

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-user-bundle#101]
Dependency injection of the bundle has a dependency with open-orchestra-cms-bundle introduced in commit https://github.com/open-orchestra/open-orchestra-user-bundle/commit/b884f2b70537cdb501c3e3cdfec330aed6553416 .

It is not possible to use this bundle in a front context due to this dependency.

**Comment by alavieille** [comment]
This is fixed in these PR for branch master:
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/102
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1645

and for branch 1.1:
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/103
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1646

thanks

**Comment by itkg-canne** [comment]
:+1:
